CREATE TABLE order_change_requests (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  request_no VARCHAR(40) NOT NULL UNIQUE,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(40),
  requested_by_id BIGINT,
  requested_by VARCHAR(100),
  requester_role VARCHAR(32),
  status VARCHAR(40) NOT NULL,
  reason VARCHAR(500),
  old_product_type VARCHAR(80),
  new_product_type VARCHAR(80),
  old_color_mode VARCHAR(40),
  new_color_mode VARCHAR(40),
  old_page_count INT,
  new_page_count INT,
  old_copies INT,
  new_copies INT,
  old_delivery_mode VARCHAR(40),
  new_delivery_mode VARCHAR(40),
  old_priority VARCHAR(20),
  new_priority VARCHAR(20),
  old_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  new_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_delta DECIMAL(12,2) NOT NULL DEFAULT 0,
  approved_by VARCHAR(100),
  decision_comment VARCHAR(500),
  freeze_started_at TIMESTAMP,
  freeze_ended_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
